rikudou_qr_payment:
  cz:
    # you don't have to set all three, either account and bank code or IBAN
    account: ''
    bankCode: ''
    iban: ''
    options:
      variableSymbol: ''
      specificSymbol: ''
      constantSymbol: ''
      currency: 'CZK'
      comment: ''
      repeat: 7 # how many days should the bank try to repeat the payment
      internalId: ''
      amount: 0.0
      country: 'CZ'
      dueDays: 14 # in how many days is the payment due
  sk:
    account: ''
    bankCode: ''
    iban: ''
    options:
      variableSymbol: ''
      specificSymbol: ''
      constantSymbol: ''
      currency: 'EUR'
      comment: ''
      internalId: ''
      amount: 0.0
      country: 'SK'
      swift: '' # required
      dueDays: 14
  eu:
    iban: ''
    options:
      character_set: 'utf-8' # valid options: utf-8, iso-8859-1, iso-8859-2, iso-8859-4, iso-8859-5, iso-8859-7, iso-8859-10, iso-8859-15
      bic: '' # BIC and SWIFT are the same thing, in this library swift is alias to bic and thus BIC takes precedence
      swift: ''
      beneficiary_name: ''
      amount: 0.0
      purpose: '' # see the rikudou\EuQrPayment\Sepa\Purpose class
      remittance_text: ''
      information: '' # information and comment are the same thing, information has precedence over comment
      comment: ''
      currency: 'EUR'
# uncomment the below lines to set different defaults per supported country, format is the same as for eu
#  de:
#    iban: ''
#    options:
#      character_set: 'utf-8'
#      bic: ''
#      swift: ''
#      beneficiary_name: ''
#      amount: 0.0
#      purpose: ''
#      remittance_text: ''
#      information: ''
#      comment: ''
#      currency: 'EUR'
#  at:
#    iban: ''
#    options:
#      character_set: 'utf-8'
#      bic: ''
#      swift: ''
#      beneficiary_name: ''
#      amount: 0.0
#      purpose: ''
#      remittance_text: ''
#      information: ''
#      comment: ''
#      currency: 'EUR'
#  nl:
#    iban: ''
#    options:
#      character_set: 'utf-8'
#      bic: ''
#      swift: ''
#      beneficiary_name: ''
#      amount: 0.0
#      purpose: ''
#      remittance_text: ''
#      information: ''
#      comment: ''
#      currency: 'EUR'
#  be:
#    iban: ''
#    options:
#      character_set: 'utf-8'
#      bic: ''
#      swift: ''
#      beneficiary_name: ''
#      amount: 0.0
#      purpose: ''
#      remittance_text: ''
#      information: ''
#      comment: ''
#      currency: 'EUR'
